"""Historical college WR -> NFL fantasy football dataset.

Contains college production stats, athletic measurables (combine/pro day),
draft capital, and resulting NFL fantasy output for training the prediction model.
"""

import pandas as pd
import numpy as np


def build_historical_dataset() -> pd.DataFrame:
    """Build historical dataset of college WRs and their NFL fantasy outcomes.

    Each row represents a WR prospect with:
    - College production metrics (final college season)
    - Athletic testing numbers (combine / pro day)
    - Draft capital
    - NFL fantasy output (PPR points per game, best season in first 3 years)
    """
    records = [
        # 2020 Draft Class
        {"name": "CeeDee Lamb", "college": "Oklahoma", "draft_year": 2020, "draft_round": 1, "draft_pick": 17,
         "college_rec": 62, "college_rec_yds": 1327, "college_rec_td": 14, "college_games": 13,
         "college_ypr": 21.4, "college_target_share": 0.28, "college_dom_rating": 0.35,
         "height_inches": 74, "weight_lbs": 198, "forty_yard": 4.50, "vertical_jump": 34.5,
         "broad_jump": 124, "bench_press": 15, "three_cone": 6.90, "shuttle": 4.24,
         "breakout_age": 18.8, "college_ypc": 8.1,
         "nfl_best_ppr_ppg": 19.8, "nfl_year1_ppr_ppg": 11.2, "nfl_year2_ppr_ppg": 14.5, "nfl_year3_ppr_ppg": 19.8},

        {"name": "Justin Jefferson", "college": "LSU", "draft_year": 2020, "draft_round": 1, "draft_pick": 22,
         "college_rec": 111, "college_rec_yds": 1540, "college_rec_td": 18, "college_games": 15,
         "college_ypr": 13.9, "college_target_share": 0.30, "college_dom_rating": 0.40,
         "height_inches": 73, "weight_lbs": 202, "forty_yard": 4.43, "vertical_jump": 37.5,
         "broad_jump": 126, "bench_press": 14, "three_cone": 6.92, "shuttle": 4.15,
         "breakout_age": 20.2, "college_ypc": 9.0,
         "nfl_best_ppr_ppg": 22.1, "nfl_year1_ppr_ppg": 16.8, "nfl_year2_ppr_ppg": 22.1, "nfl_year3_ppr_ppg": 20.5},

        {"name": "Jerry Jeudy", "college": "Alabama", "draft_year": 2020, "draft_round": 1, "draft_pick": 15,
         "college_rec": 77, "college_rec_yds": 1163, "college_rec_td": 10, "college_games": 13,
         "college_ypr": 15.1, "college_target_share": 0.25, "college_dom_rating": 0.30,
         "height_inches": 73, "weight_lbs": 193, "forty_yard": 4.45, "vertical_jump": 35.0,
         "broad_jump": 121, "bench_press": 12, "three_cone": 7.03, "shuttle": 4.26,
         "breakout_age": 18.9, "college_ypc": 7.6,
         "nfl_best_ppr_ppg": 14.2, "nfl_year1_ppr_ppg": 8.5, "nfl_year2_ppr_ppg": 8.9, "nfl_year3_ppr_ppg": 14.2},

        {"name": "Henry Ruggs III", "college": "Alabama", "draft_year": 2020, "draft_round": 1, "draft_pick": 12,
         "college_rec": 46, "college_rec_yds": 746, "college_rec_td": 7, "college_games": 13,
         "college_ypr": 16.2, "college_target_share": 0.16, "college_dom_rating": 0.18,
         "height_inches": 72, "weight_lbs": 188, "forty_yard": 4.27, "vertical_jump": 42.0,
         "broad_jump": 131, "bench_press": 10, "three_cone": 6.57, "shuttle": 4.00,
         "breakout_age": 19.5, "college_ypc": 6.4,
         "nfl_best_ppr_ppg": 8.5, "nfl_year1_ppr_ppg": 6.2, "nfl_year2_ppr_ppg": 8.5, "nfl_year3_ppr_ppg": 0.0},

        {"name": "Jalen Reagor", "college": "TCU", "draft_year": 2020, "draft_round": 1, "draft_pick": 21,
         "college_rec": 43, "college_rec_yds": 611, "college_rec_td": 5, "college_games": 12,
         "college_ypr": 14.2, "college_target_share": 0.24, "college_dom_rating": 0.20,
         "height_inches": 71, "weight_lbs": 197, "forty_yard": 4.47, "vertical_jump": 42.0,
         "broad_jump": 138, "bench_press": 17, "three_cone": 7.16, "shuttle": 4.34,
         "breakout_age": 19.0, "college_ypc": 5.5,
         "nfl_best_ppr_ppg": 6.1, "nfl_year1_ppr_ppg": 5.0, "nfl_year2_ppr_ppg": 6.1, "nfl_year3_ppr_ppg": 2.5},

        {"name": "Brandon Aiyuk", "college": "Arizona State", "draft_year": 2020, "draft_round": 1, "draft_pick": 25,
         "college_rec": 65, "college_rec_yds": 1192, "college_rec_td": 8, "college_games": 12,
         "college_ypr": 18.3, "college_target_share": 0.27, "college_dom_rating": 0.33,
         "height_inches": 73, "weight_lbs": 205, "forty_yard": 4.50, "vertical_jump": 40.0,
         "broad_jump": 128, "bench_press": 11, "three_cone": 6.94, "shuttle": 4.16,
         "breakout_age": 20.5, "college_ypc": 8.5,
         "nfl_best_ppr_ppg": 17.2, "nfl_year1_ppr_ppg": 12.8, "nfl_year2_ppr_ppg": 10.2, "nfl_year3_ppr_ppg": 17.2},

        {"name": "Tee Higgins", "college": "Clemson", "draft_year": 2020, "draft_round": 2, "draft_pick": 33,
         "college_rec": 59, "college_rec_yds": 1167, "college_rec_td": 13, "college_games": 15,
         "college_ypr": 19.8, "college_target_share": 0.22, "college_dom_rating": 0.28,
         "height_inches": 76, "weight_lbs": 216, "forty_yard": 4.54, "vertical_jump": 33.5,
         "broad_jump": 120, "bench_press": 13, "three_cone": 7.09, "shuttle": 4.30,
         "breakout_age": 19.5, "college_ypc": 7.8,
         "nfl_best_ppr_ppg": 16.5, "nfl_year1_ppr_ppg": 10.5, "nfl_year2_ppr_ppg": 16.5, "nfl_year3_ppr_ppg": 15.8},

        {"name": "Michael Pittman Jr.", "college": "USC", "draft_year": 2020, "draft_round": 2, "draft_pick": 34,
         "college_rec": 101, "college_rec_yds": 1275, "college_rec_td": 11, "college_games": 13,
         "college_ypr": 12.6, "college_target_share": 0.31, "college_dom_rating": 0.34,
         "height_inches": 76, "weight_lbs": 223, "forty_yard": 4.52, "vertical_jump": 36.0,
         "broad_jump": 122, "bench_press": 16, "three_cone": 7.01, "shuttle": 4.20,
         "breakout_age": 20.8, "college_ypc": 7.2,
         "nfl_best_ppr_ppg": 16.0, "nfl_year1_ppr_ppg": 5.8, "nfl_year2_ppr_ppg": 14.5, "nfl_year3_ppr_ppg": 16.0},

        {"name": "Chase Claypool", "college": "Notre Dame", "draft_year": 2020, "draft_round": 2, "draft_pick": 49,
         "college_rec": 66, "college_rec_yds": 1037, "college_rec_td": 13, "college_games": 13,
         "college_ypr": 15.7, "college_target_share": 0.26, "college_dom_rating": 0.30,
         "height_inches": 76, "weight_lbs": 238, "forty_yard": 4.42, "vertical_jump": 40.5,
         "broad_jump": 126, "bench_press": 19, "three_cone": 7.00, "shuttle": 4.22,
         "breakout_age": 20.1, "college_ypc": 7.0,
         "nfl_best_ppr_ppg": 12.5, "nfl_year1_ppr_ppg": 12.5, "nfl_year2_ppr_ppg": 8.0, "nfl_year3_ppr_ppg": 5.0},

        {"name": "Laviska Shenault Jr.", "college": "Colorado", "draft_year": 2020, "draft_round": 2, "draft_pick": 42,
         "college_rec": 56, "college_rec_yds": 764, "college_rec_td": 4, "college_games": 11,
         "college_ypr": 13.6, "college_target_share": 0.29, "college_dom_rating": 0.25,
         "height_inches": 73, "weight_lbs": 227, "forty_yard": 4.58, "vertical_jump": 36.0,
         "broad_jump": 122, "bench_press": 17, "three_cone": 7.12, "shuttle": 4.31,
         "breakout_age": 19.0, "college_ypc": 5.8,
         "nfl_best_ppr_ppg": 8.8, "nfl_year1_ppr_ppg": 8.8, "nfl_year2_ppr_ppg": 6.5, "nfl_year3_ppr_ppg": 3.0},

        # 2021 Draft Class
        {"name": "Ja'Marr Chase", "college": "LSU", "draft_year": 2021, "draft_round": 1, "draft_pick": 5,
         "college_rec": 84, "college_rec_yds": 1780, "college_rec_td": 20, "college_games": 14,
         "college_ypr": 21.2, "college_target_share": 0.28, "college_dom_rating": 0.42,
         "height_inches": 73, "weight_lbs": 201, "forty_yard": 4.38, "vertical_jump": 41.0,
         "broad_jump": 132, "bench_press": 16, "three_cone": 6.82, "shuttle": 4.07,
         "breakout_age": 19.1, "college_ypc": 9.5,
         "nfl_best_ppr_ppg": 21.5, "nfl_year1_ppr_ppg": 18.5, "nfl_year2_ppr_ppg": 14.2, "nfl_year3_ppr_ppg": 21.5},

        {"name": "Jaylen Waddle", "college": "Alabama", "draft_year": 2021, "draft_round": 1, "draft_pick": 6,
         "college_rec": 28, "college_rec_yds": 591, "college_rec_td": 4, "college_games": 6,
         "college_ypr": 21.1, "college_target_share": 0.30, "college_dom_rating": 0.32,
         "height_inches": 70, "weight_lbs": 182, "forty_yard": 4.37, "vertical_jump": 39.5,
         "broad_jump": 130, "bench_press": 11, "three_cone": 6.78, "shuttle": 4.09,
         "breakout_age": 18.7, "college_ypc": 8.2,
         "nfl_best_ppr_ppg": 17.5, "nfl_year1_ppr_ppg": 14.2, "nfl_year2_ppr_ppg": 13.5, "nfl_year3_ppr_ppg": 17.5},

        {"name": "DeVonta Smith", "college": "Alabama", "draft_year": 2021, "draft_round": 1, "draft_pick": 10,
         "college_rec": 117, "college_rec_yds": 1856, "college_rec_td": 23, "college_games": 13,
         "college_ypr": 15.9, "college_target_share": 0.33, "college_dom_rating": 0.48,
         "height_inches": 73, "weight_lbs": 170, "forty_yard": 4.39, "vertical_jump": 36.0,
         "broad_jump": 124, "bench_press": 8, "three_cone": 6.90, "shuttle": 4.12,
         "breakout_age": 19.8, "college_ypc": 9.2,
         "nfl_best_ppr_ppg": 17.8, "nfl_year1_ppr_ppg": 10.8, "nfl_year2_ppr_ppg": 13.5, "nfl_year3_ppr_ppg": 17.8},

        {"name": "Kadarius Toney", "college": "Florida", "draft_year": 2021, "draft_round": 1, "draft_pick": 20,
         "college_rec": 70, "college_rec_yds": 984, "college_rec_td": 10, "college_games": 11,
         "college_ypr": 14.1, "college_target_share": 0.29, "college_dom_rating": 0.30,
         "height_inches": 72, "weight_lbs": 193, "forty_yard": 4.39, "vertical_jump": 36.5,
         "broad_jump": 124, "bench_press": 13, "three_cone": 6.86, "shuttle": 4.10,
         "breakout_age": 20.5, "college_ypc": 6.8,
         "nfl_best_ppr_ppg": 7.5, "nfl_year1_ppr_ppg": 5.5, "nfl_year2_ppr_ppg": 7.5, "nfl_year3_ppr_ppg": 2.0},

        {"name": "Rashod Bateman", "college": "Minnesota", "draft_year": 2021, "draft_round": 1, "draft_pick": 27,
         "college_rec": 36, "college_rec_yds": 472, "college_rec_td": 2, "college_games": 5,
         "college_ypr": 13.1, "college_target_share": 0.32, "college_dom_rating": 0.28,
         "height_inches": 74, "weight_lbs": 190, "forty_yard": 4.39, "vertical_jump": 38.0,
         "broad_jump": 126, "bench_press": 12, "three_cone": 6.95, "shuttle": 4.18,
         "breakout_age": 18.5, "college_ypc": 7.5,
         "nfl_best_ppr_ppg": 9.2, "nfl_year1_ppr_ppg": 7.8, "nfl_year2_ppr_ppg": 9.2, "nfl_year3_ppr_ppg": 4.0},

        {"name": "Elijah Moore", "college": "Ole Miss", "draft_year": 2021, "draft_round": 2, "draft_pick": 34,
         "college_rec": 86, "college_rec_yds": 1193, "college_rec_td": 8, "college_games": 8,
         "college_ypr": 13.9, "college_target_share": 0.35, "college_dom_rating": 0.42,
         "height_inches": 70, "weight_lbs": 178, "forty_yard": 4.35, "vertical_jump": 36.0,
         "broad_jump": 128, "bench_press": 14, "three_cone": 6.74, "shuttle": 4.06,
         "breakout_age": 19.5, "college_ypc": 8.5,
         "nfl_best_ppr_ppg": 11.5, "nfl_year1_ppr_ppg": 11.5, "nfl_year2_ppr_ppg": 7.0, "nfl_year3_ppr_ppg": 8.5},

        {"name": "Rondale Moore", "college": "Purdue", "draft_year": 2021, "draft_round": 2, "draft_pick": 49,
         "college_rec": 35, "college_rec_yds": 270, "college_rec_td": 0, "college_games": 3,
         "college_ypr": 7.7, "college_target_share": 0.38, "college_dom_rating": 0.22,
         "height_inches": 67, "weight_lbs": 180, "forty_yard": 4.29, "vertical_jump": 42.0,
         "broad_jump": 133, "bench_press": 10, "three_cone": 6.60, "shuttle": 4.02,
         "breakout_age": 18.4, "college_ypc": 5.0,
         "nfl_best_ppr_ppg": 9.0, "nfl_year1_ppr_ppg": 6.8, "nfl_year2_ppr_ppg": 8.0, "nfl_year3_ppr_ppg": 9.0},

        {"name": "Terrace Marshall Jr.", "college": "LSU", "draft_year": 2021, "draft_round": 2, "draft_pick": 59,
         "college_rec": 48, "college_rec_yds": 731, "college_rec_td": 10, "college_games": 7,
         "college_ypr": 15.2, "college_target_share": 0.25, "college_dom_rating": 0.28,
         "height_inches": 75, "weight_lbs": 205, "forty_yard": 4.38, "vertical_jump": 34.5,
         "broad_jump": 126, "bench_press": 14, "three_cone": 7.05, "shuttle": 4.28,
         "breakout_age": 19.0, "college_ypc": 7.5,
         "nfl_best_ppr_ppg": 5.0, "nfl_year1_ppr_ppg": 3.5, "nfl_year2_ppr_ppg": 5.0, "nfl_year3_ppr_ppg": 3.0},

        # 2022 Draft Class
        {"name": "Drake London", "college": "USC", "draft_year": 2022, "draft_round": 1, "draft_pick": 8,
         "college_rec": 88, "college_rec_yds": 1084, "college_rec_td": 7, "college_games": 8,
         "college_ypr": 12.3, "college_target_share": 0.35, "college_dom_rating": 0.40,
         "height_inches": 76, "weight_lbs": 213, "forty_yard": 4.56, "vertical_jump": 33.5,
         "broad_jump": 119, "bench_press": 16, "three_cone": 7.09, "shuttle": 4.29,
         "breakout_age": 19.2, "college_ypc": 8.0,
         "nfl_best_ppr_ppg": 15.5, "nfl_year1_ppr_ppg": 11.0, "nfl_year2_ppr_ppg": 12.5, "nfl_year3_ppr_ppg": 15.5},

        {"name": "Garrett Wilson", "college": "Ohio State", "draft_year": 2022, "draft_round": 1, "draft_pick": 10,
         "college_rec": 70, "college_rec_yds": 1058, "college_rec_td": 12, "college_games": 13,
         "college_ypr": 15.1, "college_target_share": 0.24, "college_dom_rating": 0.30,
         "height_inches": 72, "weight_lbs": 183, "forty_yard": 4.38, "vertical_jump": 36.0,
         "broad_jump": 124, "bench_press": 11, "three_cone": 6.84, "shuttle": 4.12,
         "breakout_age": 19.3, "college_ypc": 7.5,
         "nfl_best_ppr_ppg": 16.2, "nfl_year1_ppr_ppg": 14.5, "nfl_year2_ppr_ppg": 16.2, "nfl_year3_ppr_ppg": 15.0},

        {"name": "Chris Olave", "college": "Ohio State", "draft_year": 2022, "draft_round": 1, "draft_pick": 11,
         "college_rec": 65, "college_rec_yds": 936, "college_rec_td": 13, "college_games": 12,
         "college_ypr": 14.4, "college_target_share": 0.22, "college_dom_rating": 0.28,
         "height_inches": 73, "weight_lbs": 187, "forty_yard": 4.39, "vertical_jump": 32.0,
         "broad_jump": 119, "bench_press": 12, "three_cone": 6.88, "shuttle": 4.15,
         "breakout_age": 20.0, "college_ypc": 7.2,
         "nfl_best_ppr_ppg": 16.8, "nfl_year1_ppr_ppg": 16.8, "nfl_year2_ppr_ppg": 12.0, "nfl_year3_ppr_ppg": 14.5},

        {"name": "Jameson Williams", "college": "Alabama", "draft_year": 2022, "draft_round": 1, "draft_pick": 12,
         "college_rec": 79, "college_rec_yds": 1572, "college_rec_td": 15, "college_games": 15,
         "college_ypr": 19.9, "college_target_share": 0.24, "college_dom_rating": 0.35,
         "height_inches": 74, "weight_lbs": 179, "forty_yard": 4.40, "vertical_jump": 37.0,
         "broad_jump": 128, "bench_press": 9, "three_cone": 6.95, "shuttle": 4.18,
         "breakout_age": 19.8, "college_ypc": 8.5,
         "nfl_best_ppr_ppg": 11.0, "nfl_year1_ppr_ppg": 3.0, "nfl_year2_ppr_ppg": 7.5, "nfl_year3_ppr_ppg": 11.0},

        {"name": "Treylon Burks", "college": "Arkansas", "draft_year": 2022, "draft_round": 1, "draft_pick": 18,
         "college_rec": 66, "college_rec_yds": 1104, "college_rec_td": 11, "college_games": 12,
         "college_ypr": 16.7, "college_target_share": 0.28, "college_dom_rating": 0.32,
         "height_inches": 74, "weight_lbs": 225, "forty_yard": 4.55, "vertical_jump": 33.0,
         "broad_jump": 117, "bench_press": 14, "three_cone": 7.28, "shuttle": 4.42,
         "breakout_age": 19.5, "college_ypc": 7.0,
         "nfl_best_ppr_ppg": 7.0, "nfl_year1_ppr_ppg": 5.5, "nfl_year2_ppr_ppg": 7.0, "nfl_year3_ppr_ppg": 4.0},

        {"name": "Christian Watson", "college": "North Dakota State", "draft_year": 2022, "draft_round": 2, "draft_pick": 34,
         "college_rec": 43, "college_rec_yds": 800, "college_rec_td": 7, "college_games": 11,
         "college_ypr": 18.6, "college_target_share": 0.26, "college_dom_rating": 0.28,
         "height_inches": 77, "weight_lbs": 208, "forty_yard": 4.36, "vertical_jump": 38.5,
         "broad_jump": 135, "bench_press": 13, "three_cone": 6.88, "shuttle": 4.14,
         "breakout_age": 20.5, "college_ypc": 7.2,
         "nfl_best_ppr_ppg": 13.5, "nfl_year1_ppr_ppg": 10.0, "nfl_year2_ppr_ppg": 13.5, "nfl_year3_ppr_ppg": 12.0},

        {"name": "George Pickens", "college": "Georgia", "draft_year": 2022, "draft_round": 2, "draft_pick": 52,
         "college_rec": 36, "college_rec_yds": 513, "college_rec_td": 5, "college_games": 11,
         "college_ypr": 14.3, "college_target_share": 0.20, "college_dom_rating": 0.18,
         "height_inches": 75, "weight_lbs": 200, "forty_yard": 4.47, "vertical_jump": 36.0,
         "broad_jump": 126, "bench_press": 11, "three_cone": 6.98, "shuttle": 4.22,
         "breakout_age": 18.5, "college_ypc": 6.5,
         "nfl_best_ppr_ppg": 14.5, "nfl_year1_ppr_ppg": 11.2, "nfl_year2_ppr_ppg": 14.5, "nfl_year3_ppr_ppg": 13.0},

        {"name": "Skyy Moore", "college": "Western Michigan", "draft_year": 2022, "draft_round": 2, "draft_pick": 54,
         "college_rec": 95, "college_rec_yds": 1292, "college_rec_td": 10, "college_games": 13,
         "college_ypr": 13.6, "college_target_share": 0.33, "college_dom_rating": 0.35,
         "height_inches": 70, "weight_lbs": 195, "forty_yard": 4.41, "vertical_jump": 36.5,
         "broad_jump": 125, "bench_press": 15, "three_cone": 6.80, "shuttle": 4.08,
         "breakout_age": 19.8, "college_ypc": 7.8,
         "nfl_best_ppr_ppg": 5.5, "nfl_year1_ppr_ppg": 3.8, "nfl_year2_ppr_ppg": 5.5, "nfl_year3_ppr_ppg": 4.0},

        # 2023 Draft Class
        {"name": "Jaxon Smith-Njigba", "college": "Ohio State", "draft_year": 2023, "draft_round": 1, "draft_pick": 20,
         "college_rec": 43, "college_rec_yds": 516, "college_rec_td": 4, "college_games": 6,
         "college_ypr": 12.0, "college_target_share": 0.30, "college_dom_rating": 0.28,
         "height_inches": 72, "weight_lbs": 196, "forty_yard": 4.52, "vertical_jump": 34.5,
         "broad_jump": 121, "bench_press": 12, "three_cone": 6.92, "shuttle": 4.18,
         "breakout_age": 19.0, "college_ypc": 7.0,
         "nfl_best_ppr_ppg": 14.0, "nfl_year1_ppr_ppg": 10.5, "nfl_year2_ppr_ppg": 14.0, "nfl_year3_ppr_ppg": 0.0},

        {"name": "Quentin Johnston", "college": "TCU", "draft_year": 2023, "draft_round": 1, "draft_pick": 21,
         "college_rec": 60, "college_rec_yds": 1069, "college_rec_td": 6, "college_games": 15,
         "college_ypr": 17.8, "college_target_share": 0.22, "college_dom_rating": 0.24,
         "height_inches": 76, "weight_lbs": 208, "forty_yard": 4.52, "vertical_jump": 35.0,
         "broad_jump": 122, "bench_press": 12, "three_cone": 7.12, "shuttle": 4.30,
         "breakout_age": 20.0, "college_ypc": 6.8,
         "nfl_best_ppr_ppg": 6.5, "nfl_year1_ppr_ppg": 4.5, "nfl_year2_ppr_ppg": 6.5, "nfl_year3_ppr_ppg": 0.0},

        {"name": "Zay Flowers", "college": "Boston College", "draft_year": 2023, "draft_round": 1, "draft_pick": 22,
         "college_rec": 78, "college_rec_yds": 1077, "college_rec_td": 12, "college_games": 12,
         "college_ypr": 13.8, "college_target_share": 0.31, "college_dom_rating": 0.32,
         "height_inches": 70, "weight_lbs": 182, "forty_yard": 4.42, "vertical_jump": 37.0,
         "broad_jump": 128, "bench_press": 13, "three_cone": 6.75, "shuttle": 4.05,
         "breakout_age": 19.5, "college_ypc": 7.5,
         "nfl_best_ppr_ppg": 14.5, "nfl_year1_ppr_ppg": 14.5, "nfl_year2_ppr_ppg": 13.0, "nfl_year3_ppr_ppg": 0.0},

        # 2019 Draft Class
        {"name": "Marquise Brown", "college": "Oklahoma", "draft_year": 2019, "draft_round": 1, "draft_pick": 25,
         "college_rec": 75, "college_rec_yds": 1318, "college_rec_td": 10, "college_games": 13,
         "college_ypr": 17.6, "college_target_share": 0.27, "college_dom_rating": 0.34,
         "height_inches": 69, "weight_lbs": 170, "forty_yard": 4.33, "vertical_jump": 36.5,
         "broad_jump": 120, "bench_press": 7, "three_cone": 6.72, "shuttle": 4.05,
         "breakout_age": 19.5, "college_ypc": 8.2,
         "nfl_best_ppr_ppg": 15.5, "nfl_year1_ppr_ppg": 8.5, "nfl_year2_ppr_ppg": 13.8, "nfl_year3_ppr_ppg": 15.5},

        {"name": "N'Keal Harry", "college": "Arizona State", "draft_year": 2019, "draft_round": 1, "draft_pick": 32,
         "college_rec": 73, "college_rec_yds": 1088, "college_rec_td": 9, "college_games": 12,
         "college_ypr": 14.9, "college_target_share": 0.28, "college_dom_rating": 0.30,
         "height_inches": 76, "weight_lbs": 225, "forty_yard": 4.53, "vertical_jump": 38.5,
         "broad_jump": 123, "bench_press": 17, "three_cone": 7.11, "shuttle": 4.35,
         "breakout_age": 19.0, "college_ypc": 6.5,
         "nfl_best_ppr_ppg": 4.5, "nfl_year1_ppr_ppg": 3.0, "nfl_year2_ppr_ppg": 4.5, "nfl_year3_ppr_ppg": 2.5},

        {"name": "DK Metcalf", "college": "Ole Miss", "draft_year": 2019, "draft_round": 2, "draft_pick": 64,
         "college_rec": 26, "college_rec_yds": 569, "college_rec_td": 5, "college_games": 7,
         "college_ypr": 21.9, "college_target_share": 0.22, "college_dom_rating": 0.25,
         "height_inches": 76, "weight_lbs": 229, "forty_yard": 4.33, "vertical_jump": 40.5,
         "broad_jump": 135, "bench_press": 27, "three_cone": 7.38, "shuttle": 4.50,
         "breakout_age": 19.8, "college_ypc": 7.5,
         "nfl_best_ppr_ppg": 18.0, "nfl_year1_ppr_ppg": 14.5, "nfl_year2_ppr_ppg": 18.0, "nfl_year3_ppr_ppg": 15.5},

        {"name": "AJ Brown", "college": "Ole Miss", "draft_year": 2019, "draft_round": 2, "draft_pick": 51,
         "college_rec": 85, "college_rec_yds": 1320, "college_rec_td": 6, "college_games": 12,
         "college_ypr": 15.5, "college_target_share": 0.30, "college_dom_rating": 0.36,
         "height_inches": 73, "weight_lbs": 226, "forty_yard": 4.49, "vertical_jump": 36.5,
         "broad_jump": 120, "bench_press": 19, "three_cone": 7.08, "shuttle": 4.30,
         "breakout_age": 19.2, "college_ypc": 8.0,
         "nfl_best_ppr_ppg": 20.5, "nfl_year1_ppr_ppg": 15.0, "nfl_year2_ppr_ppg": 16.2, "nfl_year3_ppr_ppg": 20.5},

        {"name": "Deebo Samuel", "college": "South Carolina", "draft_year": 2019, "draft_round": 2, "draft_pick": 36,
         "college_rec": 62, "college_rec_yds": 882, "college_rec_td": 11, "college_games": 12,
         "college_ypr": 14.2, "college_target_share": 0.28, "college_dom_rating": 0.28,
         "height_inches": 72, "weight_lbs": 215, "forty_yard": 4.48, "vertical_jump": 39.0,
         "broad_jump": 126, "bench_press": 17, "three_cone": 6.96, "shuttle": 4.18,
         "breakout_age": 20.0, "college_ypc": 7.0,
         "nfl_best_ppr_ppg": 21.0, "nfl_year1_ppr_ppg": 12.5, "nfl_year2_ppr_ppg": 10.0, "nfl_year3_ppr_ppg": 21.0},

        {"name": "Mecole Hardman", "college": "Georgia", "draft_year": 2019, "draft_round": 2, "draft_pick": 56,
         "college_rec": 35, "college_rec_yds": 538, "college_rec_td": 7, "college_games": 14,
         "college_ypr": 15.4, "college_target_share": 0.14, "college_dom_rating": 0.14,
         "height_inches": 70, "weight_lbs": 187, "forty_yard": 4.33, "vertical_jump": 40.0,
         "broad_jump": 130, "bench_press": 11, "three_cone": 6.56, "shuttle": 3.96,
         "breakout_age": 20.5, "college_ypc": 5.5,
         "nfl_best_ppr_ppg": 10.0, "nfl_year1_ppr_ppg": 7.5, "nfl_year2_ppr_ppg": 10.0, "nfl_year3_ppr_ppg": 8.0},

        {"name": "Parris Campbell", "college": "Ohio State", "draft_year": 2019, "draft_round": 2, "draft_pick": 59,
         "college_rec": 90, "college_rec_yds": 1063, "college_rec_td": 12, "college_games": 14,
         "college_ypr": 11.8, "college_target_share": 0.28, "college_dom_rating": 0.28,
         "height_inches": 72, "weight_lbs": 205, "forty_yard": 4.31, "vertical_jump": 40.0,
         "broad_jump": 132, "bench_press": 15, "three_cone": 6.55, "shuttle": 3.98,
         "breakout_age": 21.0, "college_ypc": 6.5,
         "nfl_best_ppr_ppg": 10.5, "nfl_year1_ppr_ppg": 3.5, "nfl_year2_ppr_ppg": 4.0, "nfl_year3_ppr_ppg": 5.5},

        # 2018 Draft Class
        {"name": "Calvin Ridley", "college": "Alabama", "draft_year": 2018, "draft_round": 1, "draft_pick": 26,
         "college_rec": 63, "college_rec_yds": 967, "college_rec_td": 5, "college_games": 14,
         "college_ypr": 15.3, "college_target_share": 0.22, "college_dom_rating": 0.24,
         "height_inches": 73, "weight_lbs": 190, "forty_yard": 4.43, "vertical_jump": 37.5,
         "broad_jump": 126, "bench_press": 12, "three_cone": 6.88, "shuttle": 4.14,
         "breakout_age": 18.8, "college_ypc": 7.5,
         "nfl_best_ppr_ppg": 18.5, "nfl_year1_ppr_ppg": 11.5, "nfl_year2_ppr_ppg": 13.8, "nfl_year3_ppr_ppg": 18.5},

        {"name": "DJ Moore", "college": "Maryland", "draft_year": 2018, "draft_round": 1, "draft_pick": 24,
         "college_rec": 55, "college_rec_yds": 637, "college_rec_td": 3, "college_games": 10,
         "college_ypr": 11.6, "college_target_share": 0.32, "college_dom_rating": 0.25,
         "height_inches": 72, "weight_lbs": 210, "forty_yard": 4.42, "vertical_jump": 39.5,
         "broad_jump": 131, "bench_press": 18, "three_cone": 6.75, "shuttle": 4.05,
         "breakout_age": 19.5, "college_ypc": 7.0,
         "nfl_best_ppr_ppg": 17.2, "nfl_year1_ppr_ppg": 10.5, "nfl_year2_ppr_ppg": 14.0, "nfl_year3_ppr_ppg": 12.0},

        {"name": "Courtland Sutton", "college": "SMU", "draft_year": 2018, "draft_round": 2, "draft_pick": 40,
         "college_rec": 76, "college_rec_yds": 1085, "college_rec_td": 12, "college_games": 12,
         "college_ypr": 14.3, "college_target_share": 0.27, "college_dom_rating": 0.30,
         "height_inches": 76, "weight_lbs": 218, "forty_yard": 4.54, "vertical_jump": 36.0,
         "broad_jump": 124, "bench_press": 16, "three_cone": 7.05, "shuttle": 4.28,
         "breakout_age": 19.8, "college_ypc": 7.2,
         "nfl_best_ppr_ppg": 14.5, "nfl_year1_ppr_ppg": 7.0, "nfl_year2_ppr_ppg": 14.5, "nfl_year3_ppr_ppg": 5.0},

        {"name": "Christian Kirk", "college": "Texas A&M", "draft_year": 2018, "draft_round": 2, "draft_pick": 47,
         "college_rec": 69, "college_rec_yds": 927, "college_rec_td": 7, "college_games": 12,
         "college_ypr": 13.4, "college_target_share": 0.26, "college_dom_rating": 0.26,
         "height_inches": 71, "weight_lbs": 200, "forty_yard": 4.47, "vertical_jump": 35.5,
         "broad_jump": 120, "bench_press": 14, "three_cone": 6.92, "shuttle": 4.20,
         "breakout_age": 18.5, "college_ypc": 7.0,
         "nfl_best_ppr_ppg": 15.0, "nfl_year1_ppr_ppg": 9.0, "nfl_year2_ppr_ppg": 10.5, "nfl_year3_ppr_ppg": 9.5},

        {"name": "Anthony Miller", "college": "Memphis", "draft_year": 2018, "draft_round": 2, "draft_pick": 51,
         "college_rec": 96, "college_rec_yds": 1462, "college_rec_td": 18, "college_games": 13,
         "college_ypr": 15.2, "college_target_share": 0.32, "college_dom_rating": 0.38,
         "height_inches": 71, "weight_lbs": 190, "forty_yard": 4.49, "vertical_jump": 35.5,
         "broad_jump": 122, "bench_press": 13, "three_cone": 6.95, "shuttle": 4.20,
         "breakout_age": 20.5, "college_ypc": 7.5,
         "nfl_best_ppr_ppg": 8.5, "nfl_year1_ppr_ppg": 7.0, "nfl_year2_ppr_ppg": 8.5, "nfl_year3_ppr_ppg": 4.0},

        # 2024 Draft Class
        {"name": "Marvin Harrison Jr.", "college": "Ohio State", "draft_year": 2024, "draft_round": 1, "draft_pick": 4,
         "college_rec": 67, "college_rec_yds": 1211, "college_rec_td": 14, "college_games": 12,
         "college_ypr": 18.1, "college_target_share": 0.30, "college_dom_rating": 0.38,
         "height_inches": 76, "weight_lbs": 209, "forty_yard": 4.33, "vertical_jump": 39.5,
         "broad_jump": 131, "bench_press": 18, "three_cone": 6.68, "shuttle": 4.02,
         "breakout_age": 19.0, "college_ypc": 8.5,
         "nfl_best_ppr_ppg": 13.5, "nfl_year1_ppr_ppg": 13.5, "nfl_year2_ppr_ppg": 0.0, "nfl_year3_ppr_ppg": 0.0},

        {"name": "Malik Nabers", "college": "LSU", "draft_year": 2024, "draft_round": 1, "draft_pick": 6,
         "college_rec": 89, "college_rec_yds": 1569, "college_rec_td": 14, "college_games": 13,
         "college_ypr": 17.6, "college_target_share": 0.30, "college_dom_rating": 0.40,
         "height_inches": 72, "weight_lbs": 200, "forty_yard": 4.35, "vertical_jump": 39.0,
         "broad_jump": 130, "bench_press": 14, "three_cone": 6.72, "shuttle": 4.05,
         "breakout_age": 19.2, "college_ypc": 8.5,
         "nfl_best_ppr_ppg": 16.0, "nfl_year1_ppr_ppg": 16.0, "nfl_year2_ppr_ppg": 0.0, "nfl_year3_ppr_ppg": 0.0},

        {"name": "Rome Odunze", "college": "Washington", "draft_year": 2024, "draft_round": 1, "draft_pick": 9,
         "college_rec": 92, "college_rec_yds": 1640, "college_rec_td": 13, "college_games": 14,
         "college_ypr": 17.8, "college_target_share": 0.28, "college_dom_rating": 0.38,
         "height_inches": 75, "weight_lbs": 212, "forty_yard": 4.45, "vertical_jump": 38.0,
         "broad_jump": 128, "bench_press": 16, "three_cone": 6.95, "shuttle": 4.18,
         "breakout_age": 20.0, "college_ypc": 8.0,
         "nfl_best_ppr_ppg": 10.0, "nfl_year1_ppr_ppg": 10.0, "nfl_year2_ppr_ppg": 0.0, "nfl_year3_ppr_ppg": 0.0},

        {"name": "Brian Thomas Jr.", "college": "LSU", "draft_year": 2024, "draft_round": 1, "draft_pick": 23,
         "college_rec": 68, "college_rec_yds": 1177, "college_rec_td": 17, "college_games": 13,
         "college_ypr": 17.3, "college_target_share": 0.25, "college_dom_rating": 0.32,
         "height_inches": 75, "weight_lbs": 209, "forty_yard": 4.33, "vertical_jump": 40.0,
         "broad_jump": 133, "bench_press": 14, "three_cone": 6.72, "shuttle": 4.08,
         "breakout_age": 20.0, "college_ypc": 8.0,
         "nfl_best_ppr_ppg": 14.8, "nfl_year1_ppr_ppg": 14.8, "nfl_year2_ppr_ppg": 0.0, "nfl_year3_ppr_ppg": 0.0},

        {"name": "Ladd McConkey", "college": "Georgia", "draft_year": 2024, "draft_round": 2, "draft_pick": 34,
         "college_rec": 58, "college_rec_yds": 897, "college_rec_td": 7, "college_games": 12,
         "college_ypr": 15.5, "college_target_share": 0.24, "college_dom_rating": 0.26,
         "height_inches": 72, "weight_lbs": 186, "forty_yard": 4.39, "vertical_jump": 38.5,
         "broad_jump": 128, "bench_press": 12, "three_cone": 6.80, "shuttle": 4.08,
         "breakout_age": 19.8, "college_ypc": 7.0,
         "nfl_best_ppr_ppg": 15.5, "nfl_year1_ppr_ppg": 15.5, "nfl_year2_ppr_ppg": 0.0, "nfl_year3_ppr_ppg": 0.0},

        {"name": "Xavier Worthy", "college": "Texas", "draft_year": 2024, "draft_round": 1, "draft_pick": 28,
         "college_rec": 75, "college_rec_yds": 1014, "college_rec_td": 5, "college_games": 12,
         "college_ypr": 13.5, "college_target_share": 0.26, "college_dom_rating": 0.28,
         "height_inches": 71, "weight_lbs": 165, "forty_yard": 4.21, "vertical_jump": 41.0,
         "broad_jump": 132, "bench_press": 7, "three_cone": 6.52, "shuttle": 3.92,
         "breakout_age": 19.0, "college_ypc": 7.2,
         "nfl_best_ppr_ppg": 11.0, "nfl_year1_ppr_ppg": 11.0, "nfl_year2_ppr_ppg": 0.0, "nfl_year3_ppr_ppg": 0.0},

        {"name": "Adonai Mitchell", "college": "Texas", "draft_year": 2024, "draft_round": 2, "draft_pick": 52,
         "college_rec": 56, "college_rec_yds": 845, "college_rec_td": 11, "college_games": 12,
         "college_ypr": 15.1, "college_target_share": 0.22, "college_dom_rating": 0.24,
         "height_inches": 74, "weight_lbs": 205, "forty_yard": 4.44, "vertical_jump": 38.5,
         "broad_jump": 130, "bench_press": 14, "three_cone": 6.90, "shuttle": 4.15,
         "breakout_age": 19.5, "college_ypc": 7.0,
         "nfl_best_ppr_ppg": 6.0, "nfl_year1_ppr_ppg": 6.0, "nfl_year2_ppr_ppg": 0.0, "nfl_year3_ppr_ppg": 0.0},

        # More 2018-2019 prospects for training depth
        {"name": "Mike Williams", "college": "Clemson", "draft_year": 2017, "draft_round": 1, "draft_pick": 7,
         "college_rec": 98, "college_rec_yds": 1361, "college_rec_td": 11, "college_games": 15,
         "college_ypr": 13.9, "college_target_share": 0.28, "college_dom_rating": 0.30,
         "height_inches": 76, "weight_lbs": 218, "forty_yard": 4.49, "vertical_jump": 32.5,
         "broad_jump": 121, "bench_press": 15, "three_cone": 7.10, "shuttle": 4.32,
         "breakout_age": 19.5, "college_ypc": 7.0,
         "nfl_best_ppr_ppg": 15.5, "nfl_year1_ppr_ppg": 5.5, "nfl_year2_ppr_ppg": 10.5, "nfl_year3_ppr_ppg": 15.5},

        {"name": "Corey Davis", "college": "Western Michigan", "draft_year": 2017, "draft_round": 1, "draft_pick": 5,
         "college_rec": 97, "college_rec_yds": 1500, "college_rec_td": 19, "college_games": 14,
         "college_ypr": 15.5, "college_target_share": 0.33, "college_dom_rating": 0.38,
         "height_inches": 75, "weight_lbs": 209, "forty_yard": 4.48, "vertical_jump": 37.5,
         "broad_jump": 126, "bench_press": 14, "three_cone": 6.99, "shuttle": 4.20,
         "breakout_age": 19.0, "college_ypc": 8.0,
         "nfl_best_ppr_ppg": 13.0, "nfl_year1_ppr_ppg": 5.0, "nfl_year2_ppr_ppg": 7.5, "nfl_year3_ppr_ppg": 10.0},

        {"name": "John Ross", "college": "Washington", "draft_year": 2017, "draft_round": 1, "draft_pick": 9,
         "college_rec": 81, "college_rec_yds": 1150, "college_rec_td": 17, "college_games": 14,
         "college_ypr": 14.2, "college_target_share": 0.27, "college_dom_rating": 0.28,
         "height_inches": 71, "weight_lbs": 188, "forty_yard": 4.22, "vertical_jump": 36.5,
         "broad_jump": 130, "bench_press": 10, "three_cone": 6.65, "shuttle": 4.00,
         "breakout_age": 20.0, "college_ypc": 6.5,
         "nfl_best_ppr_ppg": 8.5, "nfl_year1_ppr_ppg": 1.5, "nfl_year2_ppr_ppg": 3.0, "nfl_year3_ppr_ppg": 8.5},

        {"name": "Terry McLaurin", "college": "Ohio State", "draft_year": 2019, "draft_round": 3, "draft_pick": 76,
         "college_rec": 35, "college_rec_yds": 701, "college_rec_td": 11, "college_games": 14,
         "college_ypr": 20.0, "college_target_share": 0.15, "college_dom_rating": 0.18,
         "height_inches": 72, "weight_lbs": 208, "forty_yard": 4.35, "vertical_jump": 36.5,
         "broad_jump": 125, "bench_press": 18, "three_cone": 6.78, "shuttle": 4.10,
         "breakout_age": 21.5, "college_ypc": 6.5,
         "nfl_best_ppr_ppg": 17.5, "nfl_year1_ppr_ppg": 13.0, "nfl_year2_ppr_ppg": 16.0, "nfl_year3_ppr_ppg": 17.5},

        {"name": "Diontae Johnson", "college": "Toledo", "draft_year": 2019, "draft_round": 3, "draft_pick": 66,
         "college_rec": 69, "college_rec_yds": 1103, "college_rec_td": 13, "college_games": 14,
         "college_ypr": 16.0, "college_target_share": 0.30, "college_dom_rating": 0.30,
         "height_inches": 70, "weight_lbs": 183, "forty_yard": 4.53, "vertical_jump": 39.0,
         "broad_jump": 124, "bench_press": 11, "three_cone": 6.90, "shuttle": 4.15,
         "breakout_age": 20.0, "college_ypc": 7.0,
         "nfl_best_ppr_ppg": 17.0, "nfl_year1_ppr_ppg": 9.5, "nfl_year2_ppr_ppg": 17.0, "nfl_year3_ppr_ppg": 15.5},

        {"name": "Amon-Ra St. Brown", "college": "USC", "draft_year": 2021, "draft_round": 4, "draft_pick": 112,
         "college_rec": 41, "college_rec_yds": 478, "college_rec_td": 7, "college_games": 6,
         "college_ypr": 11.7, "college_target_share": 0.32, "college_dom_rating": 0.26,
         "height_inches": 72, "weight_lbs": 197, "forty_yard": 4.51, "vertical_jump": 35.0,
         "broad_jump": 122, "bench_press": 14, "three_cone": 6.88, "shuttle": 4.14,
         "breakout_age": 18.5, "college_ypc": 7.0,
         "nfl_best_ppr_ppg": 21.0, "nfl_year1_ppr_ppg": 9.0, "nfl_year2_ppr_ppg": 21.0, "nfl_year3_ppr_ppg": 20.0},

        {"name": "Nico Collins", "college": "Michigan", "draft_year": 2021, "draft_round": 3, "draft_pick": 89,
         "college_rec": 37, "college_rec_yds": 729, "college_rec_td": 7, "college_games": 10,
         "college_ypr": 19.7, "college_target_share": 0.20, "college_dom_rating": 0.22,
         "height_inches": 76, "weight_lbs": 215, "forty_yard": 4.43, "vertical_jump": 38.0,
         "broad_jump": 130, "bench_press": 16, "three_cone": 7.00, "shuttle": 4.22,
         "breakout_age": 19.0, "college_ypc": 6.5,
         "nfl_best_ppr_ppg": 20.5, "nfl_year1_ppr_ppg": 4.5, "nfl_year2_ppr_ppg": 8.0, "nfl_year3_ppr_ppg": 20.5},

        {"name": "Puka Nacua", "college": "BYU", "draft_year": 2023, "draft_round": 5, "draft_pick": 177,
         "college_rec": 48, "college_rec_yds": 625, "college_rec_td": 5, "college_games": 9,
         "college_ypr": 13.0, "college_target_share": 0.26, "college_dom_rating": 0.24,
         "height_inches": 74, "weight_lbs": 205, "forty_yard": 4.44, "vertical_jump": 36.5,
         "broad_jump": 126, "bench_press": 14, "three_cone": 6.90, "shuttle": 4.16,
         "breakout_age": 19.5, "college_ypc": 6.5,
         "nfl_best_ppr_ppg": 20.0, "nfl_year1_ppr_ppg": 20.0, "nfl_year2_ppr_ppg": 15.0, "nfl_year3_ppr_ppg": 0.0},
    ]

    return pd.DataFrame(records)


def get_sample_prospects() -> pd.DataFrame:
    """Return sample 2025 draft class prospects for prediction.

    These represent incoming college WRs entering the NFL draft.
    Users can also input custom prospect data via the UI.
    """
    prospects = [
        {"name": "Tetairoa McMillan", "college": "Arizona", "draft_year": 2025, "draft_round": 1, "draft_pick": 10,
         "college_rec": 84, "college_rec_yds": 1319, "college_rec_td": 8, "college_games": 12,
         "college_ypr": 15.7, "college_target_share": 0.32, "college_dom_rating": 0.38,
         "height_inches": 77, "weight_lbs": 212, "forty_yard": 4.45, "vertical_jump": 38.0,
         "broad_jump": 128, "bench_press": 15, "three_cone": 6.92, "shuttle": 4.18,
         "breakout_age": 18.5, "college_ypc": 8.5},

        {"name": "Luther Burden III", "college": "Missouri", "draft_year": 2025, "draft_round": 1, "draft_pick": 15,
         "college_rec": 61, "college_rec_yds": 676, "college_rec_td": 6, "college_games": 10,
         "college_ypr": 11.1, "college_target_share": 0.30, "college_dom_rating": 0.28,
         "height_inches": 71, "weight_lbs": 208, "forty_yard": 4.42, "vertical_jump": 40.5,
         "broad_jump": 130, "bench_press": 17, "three_cone": 6.70, "shuttle": 4.04,
         "breakout_age": 18.2, "college_ypc": 7.0},

        {"name": "Travis Hunter", "college": "Colorado", "draft_year": 2025, "draft_round": 1, "draft_pick": 2,
         "college_rec": 96, "college_rec_yds": 1258, "college_rec_td": 15, "college_games": 12,
         "college_ypr": 13.1, "college_target_share": 0.34, "college_dom_rating": 0.38,
         "height_inches": 73, "weight_lbs": 185, "forty_yard": 4.32, "vertical_jump": 42.0,
         "broad_jump": 134, "bench_press": 13, "three_cone": 6.62, "shuttle": 3.98,
         "breakout_age": 18.0, "college_ypc": 8.0},

        {"name": "Emeka Egbuka", "college": "Ohio State", "draft_year": 2025, "draft_round": 1, "draft_pick": 22,
         "college_rec": 66, "college_rec_yds": 894, "college_rec_td": 10, "college_games": 13,
         "college_ypr": 13.5, "college_target_share": 0.24, "college_dom_rating": 0.26,
         "height_inches": 73, "weight_lbs": 205, "forty_yard": 4.45, "vertical_jump": 36.5,
         "broad_jump": 126, "bench_press": 14, "three_cone": 6.88, "shuttle": 4.14,
         "breakout_age": 19.5, "college_ypc": 7.5},

        {"name": "Matthew Golden", "college": "Texas", "draft_year": 2025, "draft_round": 2, "draft_pick": 40,
         "college_rec": 61, "college_rec_yds": 987, "college_rec_td": 8, "college_games": 12,
         "college_ypr": 16.2, "college_target_share": 0.24, "college_dom_rating": 0.28,
         "height_inches": 72, "weight_lbs": 195, "forty_yard": 4.38, "vertical_jump": 38.0,
         "broad_jump": 128, "bench_press": 12, "three_cone": 6.78, "shuttle": 4.08,
         "breakout_age": 19.5, "college_ypc": 7.5},

        {"name": "Tre Harris", "college": "Ole Miss", "draft_year": 2025, "draft_round": 2, "draft_pick": 38,
         "college_rec": 70, "college_rec_yds": 1030, "college_rec_td": 7, "college_games": 10,
         "college_ypr": 14.7, "college_target_share": 0.33, "college_dom_rating": 0.35,
         "height_inches": 75, "weight_lbs": 205, "forty_yard": 4.48, "vertical_jump": 37.0,
         "broad_jump": 125, "bench_press": 15, "three_cone": 6.95, "shuttle": 4.20,
         "breakout_age": 21.0, "college_ypc": 7.8},
    ]
    return pd.DataFrame(prospects)
